name: Build and Deploy Storybook

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Check Changed Files ğŸ‘€
        uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            frontend:
              - 'frontend/components/**'

      - name: Install dependencies and build ğŸ”§
        if: steps.filter.outputs.frontend == 'true'
        run: | # Install npm packages and build the Storybook files
          cd frontend
          npm install
          cd components
          npx msw init
          npm run build:storybook:radiant
          cp stories/public/mockServiceWorker.js storybook-static/

      - name: Deploy ğŸš€
        if: steps.filter.outputs.frontend == 'true' && github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: storybook
          folder: frontend/components/storybook-static
          clean: true
          target-folder: docs
